name: Deploy News Site

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

permissions:
  contents: write # Needed to write to gh-pages branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # We need to checkout the theme submodule
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Install Hugo CLI
        env:
          HUGO_VERSION: 0.128.0
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb
          sudo dpkg -i ${{ runner.temp }}/hugo.deb
          echo "HUGO_EXEC_PATH=$(which hugo)" >> $GITHUB_ENV

      - name: Run Deployment Script
        env:
          # This token is provided by GitHub Actions and has the necessary permissions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # The repository name is automatically available from the context
          REPO: ${{ github.repository }}
          # These must be configured as Repository Secrets in your GitHub settings
          DOMAIN: ${{ secrets.DOMAIN }}
          RSS_QUERY: ${{ secrets.RSS_QUERY }}
        run: python deploy.py